### ISSUE TITLE
Piglet Controls.IntInput allows invalid input

### ISSUE THREAD

**Issue by endeavour** [dotnet-websharper/piglets#9]
You can enter non numeric characters into the piglet controls.IntInput if you type fast enough.

You can see this on the sample page (http://www.websharper.com/samples/Piglet) by entering, for example, "0asdfjkasdflkas" into the quantity field (just press 0 and then hit a bunch of letter keys).

**Comment by granicz** [comment]
Old issues are fun :) Piglets are now available as `WebSharper.Forms` - and are reimplemented on top of WebSharper UI, so you get reactivity (including basic bound UI controls, etc.) for free. The piglet sample you linked is no longer available, instead try any piglet snippets on Try WebSharper, say this one: https://try.websharper.com/snippet/adam.granicz/00004Q

Here, note the use of `Doc.Input` and friends, and although the sample does not use `Doc.IntInput`, that API is also available. The issue you reported should no longer exist.

**Comment by granicz** [comment]
@Tarmil, this issue should be in Forms as I don't think we have any plans to maintain plain piglets. Or?
